export const defaultExperience = {
  identity: {
    siteName: "PlayInvest",
    tagline: "Aposte e Invista",
    footerText: "© 2024 PlayInvest. Todos os direitos reservados.",
    footerDescription: "O grupo PLAYINVEST é uma das mais renomadas empresas internacionais de operação de iGaming, oferecendo os principais jogos slots e uma modalidade exclusiva onde VOCÊ nunca perde e ao invés disso transforma seus depósitos em retorno financeiro. Estamos autorizados e regulamentados pelo governo de Curaçao, operando com a licença número Antillephone emitida para a 8048/JAZ. Passamos por todas as verificações.",
    supportEmail: "suporte@playinvest.com",
    whatsapp: "5511999999999",
    telegramButtonLink: "",
    socialLinks: {
      instagram: "https://instagram.com/playinvest",
      telegram: "https://t.me/playinvest",
      youtube: "",
    },
  },
  seo: {
    title: "PlayInvest - Apostas e Investimentos",
    description: "A melhor plataforma de apostas e investimentos do Brasil",
    keywords: "apostas, investimentos, jogos, cassino, slots",
  },
  theme: {
    primaryColor: "#00faff",
    secondaryColor: "#0a1628",
    accentColor: "#00ff88",
    highlightIconColor: "#f97316",
    favoriteIconColor: "#facc15",
    loaderBackgroundColor: "#050f1f",
    loaderSpinnerColor: "#00faff",
    preset: "cyan",
  },
  media: {
    logo: {
      url: "/logo-horizontal.png",
      alt: "Logotipo PlayInvest",
    },
    favicon: {
      url: "/favicon.ico",
    },
    loaderGifUrl: "",
    telegramButtonImageUrl: "",
    banners: [
      {
        id: "hero",
        title: "Banner Principal",
        subtitle: "Aposte no futuro",
        ctaLabel: "Depositar agora",
        ctaLink: "/depositar",
        imageUrl: "/banners/banner-default.jpg",
        active: true,
      },
    ],
  },
  features: {
    showTelegramButton: true,
    showSupport: true,
    showPromoBar: true,
    enableInvestments: true,
    maintenanceMode: false,
  },
  navigation: {
    bottomNav: [
      {
        id: "home",
        label: "Games",
        icon: "gamepad",
        href: "/",
        enabled: true,
        isMandatory: true,
      },
      {
        id: "associate",
        label: "Associado",
        icon: "users",
        href: "/associado",
        enabled: false,
        isMandatory: false,
      },
      {
        id: "wallet",
        label: "Carteira",
        icon: "wallet",
        href: "/carteira",
        enabled: true,
        isMandatory: true,
        requiresAuth: true,
      },
      {
        id: "promotions",
        label: "Promoções",
        icon: "sparkles",
        href: "/promocoes",
        enabled: false,
        isMandatory: false,
      },
      {
        id: "profile",
        label: "Perfil",
        icon: "user",
        href: "/perfil",
        enabled: true,
        isMandatory: true,
        requiresAuth: true,
      },
    ],
  },
};

export const defaultSettings = {
  general: {
    siteName: "PlayInvest",
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",
    maintenanceMode: false,
    allowRegistration: true,
    requireEmailVerification: true,
    requireKYC: false,
    minAge: 18,
    gameColumns: 3,
  },
  branding: {
    logoUrl: "/logo-horizontal.png",
    mobileBannerUrl: "",
  },
  experience: defaultExperience,
};
